# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c2ebdabf979b3002883c9f90ed5fab685845490aeadabc575ad27b60e166542b24b1281a8a3d5824599771e5b433c46d9a92042c84ad1244640383a8252c42

test:
  secret_key_base: 9831fcd6a4e135e4c22a7f7185c865cfe5d14609e9428f21002c4535887703e38184ec645924aadd6a2c2712e5f22e4afab7afd6513fc1b52b8f5de3a2b5ceda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
